name: ft-transcendence

version: "3"
services:
  www:
    image: ft-transcendence_www
    build:
      context: ./www
      dockerfile: Containerfile
    restart: always
    depends_on:
      - db
      - storage
    networks:
      - db
      - storage
    volumes:
      - api-keys:/tmp/api-keys
    environment:
      DATABASE_URL: postgres://root:mysecretpassword@db:5432/local
    ports:
      - "8000:8000"
  db:
    image: postgres:18
    restart: always
    networks:
      - db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready"]
  storage:
    image: ft-transcendence_garage
    build:
      context: ./garage
      dockerfile: Containerfile
    restart: always
    networks:
      - storage
    ports:
      - 3900:3900
    volumes:
      - ./garage/config.toml:/etc/garage.toml:ro
      - storage-meta:/var/lib/garage/meta
      - storage-data:/var/lib/garage/data
      - api-keys:/tmp/api-keys
    healthcheck:
      test: ["CMD", "garage", "status"]

volumes:
  db-data:
  storage-meta:
  storage-data:
  api-keys:

networks:
  db:
    driver: bridge
  storage:
    driver: bridge
