name: ft-transcendence

version: "3"
services:
  rproxy:
    image: caddy:2.11
    restart: always
    networks:
      - www
      - ws
      - storage
    ports:
      - "8000:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    env_file: .env
  www:
    image: ft-transcendence_www
    build:
      context: ./www
      dockerfile: Containerfile
    restart: always
    depends_on:
      - db
      - storage
    networks:
      - www
      - db
      - storage
    env_file: .env
  ws:
    image: ft-transcendence_ws
    build:
      context: ./www
      dockerfile: Containerfile
      target: ws
    restart: always
    depends_on:
      - db
    networks:
      - ws
      - db
    env_file: .env
  db:
    image: postgres:18
    restart: always
    networks:
      - db
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "local"]
  storage:
    image: ft-transcendence_garage
    build:
      context: ./garage
      dockerfile: Containerfile
    restart: always
    networks:
      - storage
    volumes:
      - ./garage/config.toml:/etc/garage.toml:ro
      - storage-meta:/var/lib/garage/meta
      - storage-data:/var/lib/garage/data
    env_file: .env
    healthcheck:
      test: ["CMD", "garage", "status"]

volumes:
  db-data:
  storage-meta:
  storage-data:

networks:
  www:
    driver: bridge
  ws:
    driver: bridge
  db:
    driver: bridge
  storage:
    driver: bridge
