metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "31982a4b5821941b21c6610f3cfd343756012bebccf95ba7553afa569ff16514"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage"

[admin]
api_bind_addr = "[::]:3902"
admin_token = "z1jIUG2o7+x2u6jz9ldPVrzi1Hxqop+HvpjSjizHfK8="
metrics_token = "Muo36CQW+iY4kqAJaIYOibdOR2ButFCdwN9+VJKJ2N4="
