name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: v1.3.5

      - name: Run Biome
        run: bun run biome:ci
        working-directory: ./www

      - name: Setup SvelteKit
        run: bun run sv:prepare
        working-directory: ./www

      # - name: Run typescript check
        #   run: bun run ts:check
      #   working-directory: ./www

      - name: Run svelte-check # TODO svelte-check vs tsc --noEmit ?
        run: bun run sv:check
        working-directory: ./www

      # - name: Run tests
      #   run: bun test
      #   working-directory: ./www
