name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.6.3

      - name: Setup SvelteKit
        run: deno task prepare
        working-directory: ./www

      - name: Verify formatting
        run: deno fmt --check
        working-directory: ./www
  
      - name: Run deno check
        run: deno check
        working-directory: ./www
        
      - name: Run svelte-check
        run: deno task sv-check
        working-directory: ./www

      - name: Run linter
        run: deno lint
        working-directory: ./www

      # - name: Run tests
      #   run: deno test -A
      #   working-directory: ./www
